Attempt to fix Windows build error in PR 47974
- Pass vector types to function by reference instead of by value.
- Error was: "error C2719: formal parameter with requested alignment of
  128 won't be aligned".